version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start

  mysql:
    image: mysql
    restart: always
    ports:
      - 5001:3306
    environment:
      MYSQL_DATABASE: product-listing-app
      MYSQL_ROOT_PASSWORD: Hpe123
    volumes:
      - setup.sql:/docker-entrypoint-initdb.d/setup.sql
volumes:
    setup.sql: